# Generated by Django 6.0.6 on 2026-06-22 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataimport", "0002_vehicaledataimport_dealer"),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleDataImportParsingConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Vehicle data import parsing config",
                "verbose_name_plural": "Vehicle data import parsing configs",
            },
        ),
        migrations.AddField(
            model_name="vehicaledataimport",
            name="parsing_config",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="data_imports",
                to="dataimport.vehicledataimportparsingconfig",
            ),
        ),
        migrations.CreateModel(
            name="VehicleDataImportParsingConfigField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_field",
                    models.CharField(
                        choices=[
                            ("vin", "VIN"),
                            ("plate_number", "Plate number"),
                            ("year", "Year"),
                            ("make", "Make"),
                            ("model", "Model"),
                            ("exterior_color", "Exterior color"),
                            ("body_style", "Body style"),
                            ("fuel_type", "Fuel type"),
                            ("engine", "Engine"),
                            ("transmission", "Transmission"),
                        ],
                        max_length=50,
                    ),
                ),
                ("custom_field", models.CharField(max_length=255)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="dataimport.vehicledataimportparsingconfig",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle data import parsing config field",
                "verbose_name_plural": "Vehicle data import parsing config fields",
                "unique_together": {("config", "object_field")},
            },
        ),
    ]
