# Generated by Django 6.0.6 on 2026-06-29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataimport", "0007_rename_vehicle_data_import_models"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicledataimport",
            name="source",
            field=models.CharField(
                choices=[
                    ("django", "Django"),
                    ("usacar", "USA car"),
                ],
                max_length=50,
            ),
        ),
    ]
