# Generated by Django 6.0.6 on 2026-06-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0004_rename_inventorylisting_dealeroffer"),
    ]

    operations = [
        migrations.CreateModel(
            name="USACarIntegrationConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("base_url", models.URLField()),
                ("login", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                (
                    "dealer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.dealer",
                    ),
                ),
            ],
            options={
                "verbose_name": "USA Car integration config",
                "verbose_name_plural": "USA Car integration configs",
            },
        ),
    ]
