# Generated by Django 6.0.6 on 2026-06-29

from django.apps.registry import Apps
from django.db import migrations, models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def populate_config_names(
    apps: Apps,
    schema_editor: BaseDatabaseSchemaEditor,
) -> None:
    """Give existing USA Car configurations deterministic unique names."""
    config_model = apps.get_model(
        "integrations",
        "USACarIntegrationConfig",
    )
    for config in config_model.objects.all().iterator():
        config.name = f"usacar-config-{config.pk}"
        config.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usacarintegrationconfig",
            name="name",
            field=models.CharField(
                max_length=255,
                null=True,
            ),
        ),
        migrations.RunPython(
            populate_config_names,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="usacarintegrationconfig",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
            ),
        ),
    ]
