# Generated by Django 6.0.6 on 2026-06-22 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="drivetrain",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="trim",
        ),
        migrations.AddField(
            model_name="vehicle",
            name="exterior_color",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="plate_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="body_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("sedan", "Sedan"),
                    ("hatchback", "Hatchback"),
                    ("wagon", "Wagon"),
                    ("suv", "SUV"),
                    ("coupe", "Coupe"),
                    ("convertible", "Convertible"),
                    ("pickup", "Pickup"),
                    ("van", "Van"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="engine",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gasoline", "Gasoline"),
                    ("diesel", "Diesel"),
                    ("hybrid", "Hybrid"),
                    ("plug_in_hybrid", "Plug-in hybrid"),
                    ("electric", "Electric"),
                    ("lpg", "LPG"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="make",
            field=models.CharField(
                blank=True,
                choices=[
                    ("skoda", "Skoda"),
                    ("toyota", "Toyota"),
                    ("ford", "Ford"),
                    ("honda", "Honda"),
                    ("hyundai", "Hyundai"),
                    ("kia", "Kia"),
                    ("mazda", "Mazda"),
                    ("mercedes_benz", "Mercedes-Benz"),
                    ("nissan", "Nissan"),
                    ("volkswagen", "Volkswagen"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="transmission",
            field=models.CharField(
                blank=True,
                choices=[
                    ("manual", "Manual"),
                    ("automatic", "Automatic"),
                    ("cvt", "CVT"),
                    ("dual_clutch", "Dual-clutch"),
                    ("other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vin",
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
