# Generated by Django 5.2.15 on 2026-06-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dealer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "external_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("website_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name"], name="inventory_d_name_c4ba31_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "vin",
                    models.CharField(
                        blank=True, max_length=17, null=True, unique=True
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("make", models.CharField(blank=True, max_length=100)),
                ("model", models.CharField(blank=True, max_length=100)),
                ("trim", models.CharField(blank=True, max_length=100)),
                ("body_style", models.CharField(blank=True, max_length=100)),
                ("engine", models.CharField(blank=True, max_length=255)),
                ("transmission", models.CharField(blank=True, max_length=255)),
                ("drivetrain", models.CharField(blank=True, max_length=100)),
                ("fuel_type", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["make", "model", "year"],
                        name="inventory_v_make_2a5c6e_idx",
                    )
                ],
            },
        ),
    ]
