# Generated by Django 6.0.6 on 2026-06-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataimport", "0003_vehicledataimportparsingconfig_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicledataimportparsingconfig",
            name="columns_to_skip",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
